event_event:
    resource: "@EventBundle/Resources/config/routing/event.yml"
    prefix:   /event

event_homepage:
    path:     /hello/{count}/{firstName}
    defaults: { _controller: EventBundle:Default:index }
